name: Check Completeness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3
      
    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: Check duplications
      run: jscpd . --min-lines 3 --min-tokens 48 --threshold 0
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8  
        
    - name: Build and Generate coverage
      run: mvn test jacoco:report
      
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./target/site/jacoco
        retention-days: 1    
    - name: Build main
      run: mvn compile exec:java - Dexec.mainClass="main.SendData"
